//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Administration()
        {
            this.Camps = new HashSet<Camps>();
        }
    
        public long administrationID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<long> roleID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    
        public virtual AdminRoles AdminRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Camps> Camps { get; set; }
    }
}
