//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public long ID_audit { get; set; }
        public System.DateTime LogTime { get; set; }
        public bool LogResult { get; set; }
        public string Username { get; set; }
        public string IP { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
