//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contracts()
        {
            this.Invoice = new HashSet<Invoice>();
        }
    
        public long contractID { get; set; }
        public Nullable<long> parentID { get; set; }
        public long patent2ID { get; set; }
        public Nullable<long> childID { get; set; }
        public Nullable<long> campID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Balance { get; set; }
    
        public virtual Children Children { get; set; }
        public virtual Parents Parents { get; set; }
        public virtual Parents Parents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
        public virtual Camp Camp { get; set; }
    }
}
