//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camps
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SummerCampEntities : DbContext
    {
        public SummerCampEntities()
            : base("name=SummerCampEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Administration> Administration { get; set; }
        public virtual DbSet<AdminRoles> AdminRoles { get; set; }
        public virtual DbSet<Camps> Camps { get; set; }
        public virtual DbSet<Children> Children { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<FoodProvider> FoodProvider { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<Parents> Parents { get; set; }
        public virtual DbSet<Audit> Audit { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
